name: Generate Unity License Automatically 

on: workflow_dispatch

jobs:
  generate-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate License File
        uses: game-ci/unity-login@v4
        with:
          unityEmail: ${{ secrets.UNITY_EMAIL }}
          unityPassword: ${{ secrets.UNITY_PASSWORD }}

      - name: Display License Info
        run: echo "Licența a fost generată cu succes în background!"
